package com.stat_tracker.entity.plays.enums;

public enum ViolationType {
    TRAVELLING, CARRYING, DOUBLE_DRIBBLE,
    THREE_SECOND_DEF, THREE_SECOND_OFF, FIVE_SECOND, EIGHT_SECOND,
    BACK_COURT, OUT_OF_BOUNDS, FREE_THROW,
    SHOT_CLOCK, TEAM, THROW_IN, GOAL_TENDING, OTHER
}
