package com.stat_tracker.entity.plays.enums;

public enum Zone {
    BACK_COURT,
    RIGHT_CORNER_3PT, RIGHT_WING_3PT, TOP_3PT, LEFT_WING_3PT, LEFT_CORNER_3PT,
    RIGHT_CORNER_2PT, RIGHT_WING_2PT, TOP_2PT, LEFT_WING_2PT, LEFT_CORNER_2PT,
    RIGHT_LOW_POST, HIGH_POST, LEFT_LOW_POST,
    UNDER_BASKET

}
