package com.stat_tracker.entity.plays.enums;

public enum Zone {
    LEFT_CORNER, RIGHT_CORNER, LEFT_WING, RIGHT_WING, TOP_OF_THE_KEY, LEFT_SHORT_CORNER,
    RIGHT_SHORT_CORNER, LEFT_SHORT_WING, RIGHT_SHORT_WING, SHORT_TOP_OF_THE_KEY, LEFT_LOW_POST,
    RIGHT_LOW_POST, UNDER_BASKET, HIGH_POST, FREE_THROW, BACK_COURT, HALF_COURT

}
