package com.stat_tracker.entity.plays.enums;

public enum Zone {
    BACK_COURT_3PT,
    RIGHT_CORNER_3PT, RIGHT_WING_3PT, TOP_3PT, LEFT_WING_3PT, LEFT_CORNER_3PT,
    RIGHT_CORNER_2PT, RIGHT_WING_2PT, TOP_2PT, LEFT_WING_2PT, LEFT_CORNER_2PT,
    RIGHT_LOW_POST_2PT, HIGH_POST_2PT, LEFT_LOW_POST_2PT,
    UNDER_BASKET_2PT,
    FREE_THROW

}
